services: mongodb

language: php

php:
  - 5.3
  - 5.4

before_script:
  - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer --prefer-dist --dev install

script: phpunit --coverage-text
